# Generated by Django 5.2.2 on 2025-06-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
